// Optional bridge: public sort configuration + command, no explorer patches.
const CONFIG='7 Tools/Source order.md';
function compareOrder(a,b){
 for(let i=0;i<Math.min(a.length,b.length);i++){
  if(a[i]===b[i])continue;
  if(typeof a[i]==='number'&&typeof b[i]==='number')return a[i]-b[i];
  if(typeof a[i]!==typeof b[i])return typeof a[i]==='number'?-1:1;
  return String(a[i]).localeCompare(String(b[i]));
 }return a.length-b.length;
}
const safeLiteral=text=>!!text&&!/[\r\n\\*]/.test(text)&&!text.includes('...')&&!text.includes('{:')&&text.trim()===text;
function buildSpec(groups){
 const folders=new Map(),warnings=[];
 for(const {root,entries} of groups)for(const e of entries){
  if(!Array.isArray(e.sourceOrder)||!e.sourceOrder.length||e.sourceOrder.some(x=>!(typeof x==='string'||typeof x==='number'&&Number.isFinite(x))))continue;
  const file=e.workspacePath;if(!file?.startsWith(root+'/')||!file.endsWith('.md'))continue;
  const parts=file.slice(root.length+1).split('/');let parent=root;
  for(let i=0;i<parts.length;i++){
   const folder=i<parts.length-1,name=folder?parts[i]:parts[i].slice(0,-3),key=(folder?'folder:':'file:')+name;
   if(!folders.has(parent))folders.set(parent,new Map());
   const map=folders.get(parent),existing=map.get(key);
   if(!existing||compareOrder(e.sourceOrder,existing.order)<0)map.set(key,{name,folder,order:e.sourceOrder});
   parent+='/'+parts[i];
  }
 }
 const sections=[];
 for(const [folder,items] of [...folders].sort(([a],[b])=>a.localeCompare(b))){
  // The upstream grammar has wildcards. Never accidentally turn a name into a rule.
  if(!safeLiteral(folder)||[...items.values()].some(x=>!safeLiteral(x.name))){warnings.push(folder);continue;}
  const rows=[...items.values()].sort((a,b)=>compareOrder(a.order,b.order)||Number(a.folder)-Number(b.folder)||a.name.localeCompare(b.name));
  sections.push(['target-folder: '+folder,...rows.map(x=>(x.folder?'/folders ':'/:files ')+x.name),'...','  < a-z'].join('\n'));
 }
 if(!sections.length)sections.push('target-folder: 1 Working files\nsorting: standard');
 return {text:'---\nsorting-spec: |\n'+sections.join('\n\n').split('\n').map(x=>'  '+x).join('\n')+'\n---\n\n# Source order\n\nGenerated by RE Workbench. Source order applies only where supplied by the importer. New local files follow alphabetically. Disable Custom File Explorer Sorting to use normal Obsidian sorting.\n'+(warnings.length?'\nStandard sorting retained for names unsupported by the sorting grammar: '+warnings.join(', ')+'\n':''),warnings};
}
function setup(p){
 let queue=Promise.resolve();
 const reapply=()=>{const sort=p.app.plugins.plugins['custom-sort'];if(sort&&!sort.settings.suspended)p.app.commands.executeCommandById('custom-sort:enable-custom-sorting');};
 p.registerEvent(p.app.metadataCache.on('changed',file=>{if(file.path===CONFIG)reapply();}));
 p.refreshSourceSorting=(tree)=>{
  queue=queue.catch(()=>{}).then(async()=>{
   if(!p.nativeWorking)return;
   tree ||= await p.store.getTree('variant:'+p.nativeWorking.id);
   const groups=[{root:'1 Working files',entries:tree}];
   const saved=p.settings.sidebarVersion;
   if(saved){const paths=new Map(saved.entries.map(e=>[e.key,e.path]));groups.push({root:'2 Saved versions',entries:(await p.store.getTree('version:'+saved.id)).map(e=>({...e,workspacePath:paths.get(e.key)}))});}
   const {text}=buildSpec(groups),adapter=p.app.vault.adapter;
   const old=await adapter.read(CONFIG).catch(()=>null);
   if(old!==text)await adapter.write(CONFIG,text);
  });return queue;
 };
}
module.exports={buildSpec,compareOrder,setup};
